import Head from 'next/head'
import React from "react";
import {NumbersGuessedContextProvider} from "../context/NumbersGuessedContext";
import GuessNumbers from "../components/GuessNumbers";

export default function Home() {
    return (
        <>
            <Head>
                <title>Create Next App</title>
                <meta name="description" content="Generated by create next app"/>
                <meta name="viewport" content="width=device-width, initial-scale=1"/>
                <link rel="icon" href="/favicon.ico"/>
            </Head>
            <main className={"flex flex-col h-full"}>
                <NumbersGuessedContextProvider>
                    <GuessNumbers/>
                </NumbersGuessedContextProvider>
            </main>
        </>
    )
}
